# Generated by Django 4.2.4 on 2023-12-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='teste',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
